name: iOS Build

on:
  workflow_dispatch: # This allows you to start the build manually whenever you want

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Create Secrets File (Fix Compilation)
        run: |
          mkdir -p lib/core
          echo "class AppSecrets { static const String smtpEmail = 'dummy@mail.com'; static const String smtpPassword = 'dummy'; }" > lib/core/secrets.dart
          
      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS No-Codesign
        run: flutter build ios --release --no-codesign

      - name: Upload iOS Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/iphoneos
